version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_PASSWORD: rapadura
    volumes:
      - db-data:/var/lib/postgresql/data
      - gem-data:/usr/local/bundle

  pghero:
    image: ankane/pghero
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:rapadura@db:5432/template_development
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: rapadura
    volumes:
      - .:/home/app/api
    entrypoint: ./entrypoint.sh

volumes:
  db-data:
    driver: local
  gem-data:
    driver: local
