default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USERNAME") { '' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { '' } %>
  host: db

development:
  primary:
    <<: *default
    database: template_development
    host: db
  secondary:
    <<: *default
    database: template_development
    host: db_replica_1
    replica: true
  tertiary:
    <<: *default
    database: template_development
    host: db_replica_2
    replica: true

test:
  <<: *default
  database: template_test

production:
  url: <%= ENV.fetch("DATABASE_URL") { '' } %>

